#db configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost/workflo_project
    username: postgres
    password: Martins1@_
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# setting the Hibernate logging level
#logging:
#  level:
#    org:
#      hibernate: DEBUG

#  jpa:
#    database: mysql

#cloudinary service
cloudinary:
  cloud:
    name: dof34kqxr
    api:
      key: 274514264572722
      secret_key: 1fj0jeQDKCmEgZQT6uM4kiCeyXw
    resource_type: image
    folder_name: workflo


#brevo sender
brevo:
  mail:
    api:
      key: "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"
      url: "https://api.brevo.com/v3/smtp/email"