#db configuration
#Spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: Sista_1%
#    url: jdbc:mysql://localhost:3306/workflo_db
#  jpa:
#    #    show-sql: true
#    hibernate:
#      ddl-auto: update
#    generate-ddl: true
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: OnColosOnColos365
#    url: jdbc:mysql://localhost:3306/workflo_db
#  jpa:
##    show-sql: true
#    hibernate:
#      ddl-auto: create
#    generate-ddl: true
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

#cloudinary service
cloudinary:
  cloud:
    name: dof34kqxr
    api:
      key: 274514264572722
      secret_key: 1fj0jeQDKCmEgZQT6uM4kiCeyXw
    resource_type: image
    folder_name: workflo


#brevo sender
brevo:
  mail:
    api:
      key: ${BREVO_KEY}
      url: "https://api.brevo.com/v3/smtp/email"