#db configuration

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

server:
  error:
    include-message: always
    include-binding-errors: always
    include-exception: true
    include-stacktrace: always

#cloudinary service
cloudinary:
  cloud:
    name: ${CLOUDINARY_NAME}
    api:
      key: ${CLOUDINARY_KEY}
      secret_key: ${CLOUDINARY_SECRET_KEY}
    resource_type: ${CLOUDINARY_RESOURCE_TYPE}
    folder_name: ${CLOUDINARY_FOLDER_NAME}



#brevo sender
brevo:
  mail:
    api:
      key: ${BREVO_KEY}
      url: ${BREVO_URL}