#db configuration
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: OnColosOnColos365
    url: jdbc:mysql://localhost:3306/workflo_db
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create
    generate-ddl: true

#  jpa:
#    database: mysql
#  config:
#    location: classpath:/src/main/resources/workflo.yaml
#cloudinary service
cloudinary:
  cloud:
    name: dof34kqxr
    api:
      key: 274514264572722
      secret_key: 1fj0jeQDKCmEgZQT6uM4kiCeyXw
    resource_type: image
    folder_name: workflo


#brevo sender
brevo:
  mail:
    api:
      key: "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"
      url: "https://api.brevo.com/v3/smtp/email"